/**
 * Duo's spoken lines, generated by Claude through the laptop proxy.
 *
 * Replaces the fixed strings in feedbackTable.ts as the thing Duo actually
 * says. The table is still here and still matters — it is now the fallback,
 * and it is what you hear whenever the network is not fast enough or not
 * there.
 *
 * ## The key is not on the phone
 *
 * It goes to `second-voice-proxy` on the laptop, which holds ANTHROPIC_API_KEY
 * and calls the Messages API. Expo only inlines EXPO_PUBLIC_ variables and
 * anything inlined is extractable from the APK, so a key shipped in the app is
 * a key given away. The trusted proxy is the only component that holds the
 * Anthropic credential.
 *
 * ## Every call is allowed to fail
 *
 * README rule #1 says the session loop makes no network calls, and this breaks
 * that rule knowingly and on request. What it does not do is make the session
 * *depend* on the network: every request has a short deadline, and the moment
 * it passes, the local line is spoken instead.
 *
 * That matters most for the one line the demo is built on. A compensation
 * correction has to land while the person is still leaning — 01-problem-and-
 * users.md is about feedback that arrives in the moment. So the deadline for
 * corrections is tight, and missing it costs nothing: the user hears the
 * hand-written line, exactly as before, and never learns there was a model
 * involved.
 */

const DEFAULT_PORT = 8788;

/**
 * Where the proxy lives. localhost works over `adb reverse tcp:8788 tcp:8788`,
 * the same USB path the laptop viewer uses, so no venue network is involved.
 * Override with EXPO_PUBLIC_DUO_REPLY_URL for a WiFi setup.
 */
export const REPLY_URL =
  process.env.EXPO_PUBLIC_DUO_REPLY_URL ?? `http://localhost:${DEFAULT_PORT}/reply`;

/**
 * How long Duo waits for a generated line before falling back.
 *
 * MEASURED, not guessed. Against claude-haiku-4-5 through this proxy the round
 * trip is 1.08-1.26s for a reply and 1.30-1.71s for an intent, over USB with a
 * warm connection.
 *
 * The first version of this file set `urgent` to 700ms, reasoning that a
 * correction is worthless late. That number was picked before anything was
 * timed, and it was below the floor: every single compensation line silently
 * fell back to the written table and the model was never once used for the one
 * beat the demo is built on. A timeout that can never be met is not a safety
 * margin, it is dead code.
 *
 * 1800ms clears the measured range with headroom. The cost is real and worth
 * stating: a correction now lands about 1.3s after the compensation is
 * detected, on top of the 400ms the detector already waits to be sure. If that
 * proves too slow in front of people, drop this back to 700 and corrections
 * return to the instant written lines — the fallback is not a degraded mode,
 * it is the original behaviour.
 */
export const REPLY_TIMEOUT_MS = {
  urgent: 1800,
  relaxed: 3000,
} as const;

export type ReplyContext = Record<string, unknown>;

export type ReplyRequest = {
  /** What just happened, in a sentence. The model turns this into speech. */
  situation: string;
  /** Anything worth knowing: rep count, side, quality. Kept small. */
  context?: ReplyContext;
  /** The line to speak if the model does not answer in time. Always required. */
  fallback: string;
  urgency?: keyof typeof REPLY_TIMEOUT_MS;
};

/** Set false after a failure, so a dead proxy is asked once and then left alone. */
let proxyReachable = true;
let lastFailureAt = 0;

/** How long to stop asking after a failure. One retry per session-ish. */
const BACKOFF_MS = 20_000;

export type ReplyOutcome = {
  text: string;
  /** True when the line came from the model rather than the fallback table. */
  generated: boolean;
};

/**
 * Returns a line to speak. Never rejects, never returns empty: the fallback is
 * the floor. Callers can speak the result without checking anything.
 */
export async function requestReply(request: ReplyRequest): Promise<ReplyOutcome> {
  const timeoutMs = REPLY_TIMEOUT_MS[request.urgency ?? 'relaxed'];

  if (!proxyReachable && Date.now() - lastFailureAt < BACKOFF_MS) {
    return { text: request.fallback, generated: false };
  }

  try {
    // AbortSignal.timeout exists in Hermes on RN 0.86, but a manual controller
    // is used so the same code path works if it ever does not.
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    let response: Response;
    try {
      response = await fetch(REPLY_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          situation: request.situation,
          context: request.context ?? {},
          timeoutMs: Math.max(timeoutMs, 4000),
        }),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timer);
    }

    if (!response.ok) throw new Error(`reply_http_${response.status}`);
    const data = (await response.json()) as { text?: unknown };
    const text = typeof data.text === 'string' ? data.text.trim() : '';
    if (!text) throw new Error('empty_reply');

    proxyReachable = true;
    return { text, generated: true };
  } catch {
    // Deliberately silent. A slow laptop, a closed proxy or airplane mode are
    // all the same thing from here: speak the written line and carry on. The
    // dev overlay is where this becomes visible, not the patient's screen.
    proxyReachable = false;
    lastFailureAt = Date.now();
    return { text: request.fallback, generated: false };
  }
}

/** Lets the dev overlay show whether Duo is speaking its own words. */
export function replyStatus(): { reachable: boolean } {
  return { reachable: proxyReachable };
}

export type ProxyHealth =
  | { state: 'checking' }
  | { state: 'unreachable'; detail: string }
  | { state: 'ready'; model: string | null; anthropic: boolean };

/**
 * Ask the proxy whether it is there, before anything needs it to be.
 *
 * Three failures used to look identical from the phone — the laptop not
 * reachable, the proxy not running, and no API key configured — because all
 * three end with Duo speaking its written line and nothing on screen changes.
 * This separates them, costs no tokens, and runs once at startup so the answer
 * is on the dev overlay before the demo rather than after it.
 */
export async function checkProxyHealth(): Promise<ProxyHealth> {
  const url = REPLY_URL.replace(/\/reply$/, '/health');
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 4000);
  try {
    const response = await fetch(url, { signal: controller.signal });
    if (!response.ok) return { state: 'unreachable', detail: `http ${response.status}` };
    const data = (await response.json()) as { anthropic?: boolean; model?: string | null };
    proxyReachable = true;
    return {
      state: 'ready',
      anthropic: Boolean(data.anthropic),
      model: typeof data.model === 'string' ? data.model : null,
    };
  } catch (error) {
    return {
      state: 'unreachable',
      detail: error instanceof Error && error.name === 'AbortError' ? 'timeout' : 'no route',
    };
  } finally {
    clearTimeout(timer);
  }
}
