/**
 * Duo's spoken lines, generated by Claude directly in the demo build.
 *
 * Replaces the fixed strings in feedbackTable.ts as the thing Duo actually
 * says. The table is still here and still matters — it is now the fallback,
 * and it is what you hear whenever the network is not fast enough or not
 * there.
 *
 * ## Demo credential warning
 *
 * This hackathon build intentionally inlines an Anthropic key so it can call
 * Claude without a laptop proxy. Anyone with the APK can extract the key.
 * Restrict the key's spend, do not distribute the APK, and revoke it after
 * the event.
 *
 * ## Every call is allowed to fail
 *
 * README rule #1 says the session loop makes no network calls, and this breaks
 * that rule knowingly and on request. What it does not do is make the session
 * *depend* on the network: every request has a short deadline, and the moment
 * it passes, the local line is spoken instead.
 *
 * That matters most for the one line the demo is built on. A compensation
 * correction has to land while the person is still leaning — 01-problem-and-
 * users.md is about feedback that arrives in the moment. So the deadline for
 * corrections is tight, and missing it costs nothing: the user hears the
 * hand-written line, exactly as before, and never learns there was a model
 * involved.
 */

import { anthropicConfigured, anthropicModel, requestAnthropicText } from './anthropicClient';

/**
 * Prompt constraints formerly enforced by the proxy, retained in the direct
 * demo client so the model contract does not change with the transport.
 */
const DUO_SYSTEM = [
  'You are Duo, a calm rehabilitation companion for a stroke survivor doing arm exercises at home.',
  'Reply with ONE short spoken line and nothing else. No preamble, no quotes, no emoji, no markdown.',
  'Under 10 words where possible. One instruction at a time. Plain words. Never scold, diagnose, assess recovery, mention scores, or change a prescribed exercise programme.',
  'You are not a medical device and must never imply otherwise.',
].join('\n');

/**
 * How long Duo waits for a generated line before falling back.
 *
 * MEASURED, not guessed. Against claude-haiku-4-5 through this proxy the round
 * trip is 1.08-1.26s for a reply and 1.30-1.71s for an intent, over USB with a
 * warm connection.
 *
 * The first version of this file set `urgent` to 700ms, reasoning that a
 * correction is worthless late. That number was picked before anything was
 * timed, and it was below the floor: every single compensation line silently
 * fell back to the written table and the model was never once used for the one
 * beat the demo is built on. A timeout that can never be met is not a safety
 * margin, it is dead code.
 *
 * 1800ms clears the measured range with headroom. The cost is real and worth
 * stating: a correction now lands about 1.3s after the compensation is
 * detected, on top of the 400ms the detector already waits to be sure. If that
 * proves too slow in front of people, drop this back to 700 and corrections
 * return to the instant written lines — the fallback is not a degraded mode,
 * it is the original behaviour.
 */
export const REPLY_TIMEOUT_MS = {
  urgent: 1800,
  relaxed: 3000,
} as const;

export type ReplyContext = Record<string, unknown>;

export type ReplyRequest = {
  /** What just happened, in a sentence. The model turns this into speech. */
  situation: string;
  /** Anything worth knowing: rep count, side, quality. Kept small. */
  context?: ReplyContext;
  /** The line to speak if the model does not answer in time. Always required. */
  fallback: string;
  urgency?: keyof typeof REPLY_TIMEOUT_MS;
};

/** Set false after a failure, so an unavailable model is asked once then left alone. */
let proxyReachable = true;
let lastFailureAt = 0;

/** How long to stop asking after a failure. One retry per session-ish. */
const BACKOFF_MS = 20_000;

export type ReplyOutcome = {
  text: string;
  /** True when the line came from the model rather than the fallback table. */
  generated: boolean;
};

/**
 * Returns a line to speak. Never rejects, never returns empty: the fallback is
 * the floor. Callers can speak the result without checking anything.
 */
export async function requestReply(request: ReplyRequest): Promise<ReplyOutcome> {
  const timeoutMs = REPLY_TIMEOUT_MS[request.urgency ?? 'relaxed'];

  if (!proxyReachable && Date.now() - lastFailureAt < BACKOFF_MS) {
    return { text: request.fallback, generated: false };
  }

  try {
    // AbortSignal.timeout exists in Hermes on RN 0.86, but a manual controller
    // is used so the same code path works if it ever does not.
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const text = await requestAnthropicText({
        system: DUO_SYSTEM,
        user: `Situation: ${request.situation}\nSession so far: ${JSON.stringify(request.context ?? {})}\nSay the one line Duo speaks now.`,
        maxTokens: 60,
        temperature: 0.7,
        signal: controller.signal,
      });
      const cleaned = text.split('\n').map((line) => line.trim()).filter(Boolean)[0]?.replace(/^["“]+|["”]+$/g, '').trim() ?? '';
      if (!cleaned) throw new Error('empty_reply');
      proxyReachable = true;
      return { text: cleaned, generated: true };
    } finally {
      clearTimeout(timer);
    }
  } catch {
    // Deliberately silent. A slow model endpoint or airplane mode are
    // all the same thing from here: speak the written line and carry on. The
    // dev overlay is where this becomes visible, not the patient's screen.
    proxyReachable = false;
    lastFailureAt = Date.now();
    return { text: request.fallback, generated: false };
  }
}

/** Lets the dev overlay show whether Duo is speaking its own words. */
export function replyStatus(): { reachable: boolean } {
  return { reachable: proxyReachable };
}

export type ProxyHealth =
  | { state: 'checking' }
  | { state: 'unreachable'; detail: string }
  | { state: 'ready'; model: string | null; anthropic: boolean };

/**
 * Report whether this self-contained demo bundle has a Claude key.
 */
export async function checkProxyHealth(): Promise<ProxyHealth> {
  if (!anthropicConfigured) return { state: 'unreachable', detail: 'no bundled API key' };
  return { state: 'ready', anthropic: true, model: anthropicModel };
}
